apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-sample
spec:
  imageHub: "docker.io/istio"
  imageTag: "1.1.0"
  mtls: false
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useTrustworthyJwt: true
    useNormalJwt: true
  pilot:
    image: "pilot"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
  citadel:
    image: "citadel"
    replicaCount: 1
  galley:
    image: "galley"
    replicaCount: 1
  gateways:
    ingress:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceAnnotations: {}
      serviceLabels: {}
      sds:
        enabled: true
        image: "node-agent-k8s"
    egress:
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceAnnotations: {}
      serviceLabels: {}
    k8singress:
      enabled: false
  mixer:
    image: "mixer"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  sidecarInjector:
    image: "sidecar_injector"
    replicaCount: 1
  nodeAgent:
    enabled: true
    image: "node-agent-k8s"
  proxy:
    image: "proxyv2"
    enableCoreDump: false
  proxyInit:
    image: "proxy_init"
  defaultPodDisruptionBudget:
    enabled: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY

